import {useState,useEffect,useRef,useCallback,type ReactNode} from 'react';
import {House,CalendarDays,Check,CheckCheck,ShoppingBasket,Compass,LockKeyhole,Plus,ChevronLeft,ChevronRight,X,ArrowUpRight,Settings2,Heart,Leaf,MapPin,Pin,Trash2,Pencil,Search,Download,Upload,RefreshCw,LogOut,Wallet,ArrowDownLeft,ArrowUpLeft,LoaderCircle,NotebookPen,Cat,ShieldCheck} from 'lucide-react';
import {type Item,type Kind,type Person,type Transaction,kinds,categories,newItem,seedItems,validateItem,today,fromDay,dayKey,addDays,weekStart,friendlyDate,isOnDay,parseMoney,money} from './domain';
// Bu sürüm yalnızca tarayıcıda kayıt tutar; hesap ve bütçe bağlantıları kapalı.
const api = {cloud: false, configIncomplete: false, currentSession: () => null, loadItems: async (): Promise<Item[]> => [], saveItem: async (item: Item) => item, deleteItem: async (_item: Item) => {}, logout: async () => {}};

type Page='today'|'calendar'|'tasks'|'needs'|'trips'|'budget';
const nav:{id:Page;label:string;icon:typeof House}[]=[{id:'today',label:'Bugün',icon:House},{id:'calendar',label:'Takvim',icon:CalendarDays},{id:'tasks',label:'Ev işleri',icon:CheckCheck},{id:'needs',label:'İhtiyaçlar',icon:ShoppingBasket},{id:'trips',label:'Geziler',icon:Compass},{id:'budget',label:'Bütçe',icon:LockKeyhole}];
const DAYS=['Pzt','Sal','Çar','Per','Cum','Cmt','Paz'];
const STORAGE='aryaland.demo.v1';
const cx=(...v:(string|false|undefined)[])=>v.filter(Boolean).join(' ');
function IconButton({label,children,onClick,disabled=false}:{label:string;children:ReactNode;onClick:()=>void;disabled?:boolean}){return <button type="button" className="icon-button" aria-label={label} title={label} onClick={onClick} disabled={disabled}>{children}</button>}
function PersonBadge({person}:{person:Person}){return <span className={cx('person',person==='Serkan'?'serkan':person==='Rabia'?'rabia':'both')} title={person}>{person==='Birlikte'?<Heart size={13}/>:person[0]}</span>}
function Modal({title,children,onClose,wide=false}:{title:string;children:ReactNode;onClose:()=>void;wide?:boolean}){
 const ref=useRef<HTMLDialogElement>(null);const close=useRef(onClose);close.current=onClose;
 useEffect(()=>{const d=ref.current;d?.showModal();return()=>{d?.close()}},[]);
 return <dialog ref={ref} className={cx('modal',wide&&'wide')} aria-label={title} onCancel={e=>{e.preventDefault();close.current()}} onClick={e=>{if(e.target===ref.current){const r=ref.current!.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)close.current()}}}><div className="modal-head"><h2>{title}</h2><IconButton label="Kapat" onClick={onClose}><X size={20}/></IconButton></div>{children}</dialog>
}
function Empty({title,text,onAdd,label='Yeni ekle'}:{title:string;text:string;onAdd?:()=>void;label?:string}){return <div className="empty"><Cat size={36} strokeWidth={1.2}/><h3>{title}</h3><p>{text}</p>{onAdd&&<button className="button secondary" onClick={onAdd}><Plus size={16}/>{label}</button>}</div>}

function initialItems():Item[]{
 if(api.cloud||api.configIncomplete)return [];
 try{const raw=localStorage.getItem(STORAGE);if(raw){const items=JSON.parse(raw);if(!Array.isArray(items))return [];return items.map(validateItem)}const seed=seedItems();localStorage.setItem(STORAGE,JSON.stringify(seed));return seed}catch{return []}
}
function currentPage():Page {const p=location.hash.slice(1);return nav.some(n=>n.id===p)?p as Page:'today'}

export default function App(){
 const [page,setPage]=useState<Page>(currentPage);const [items,setItems]=useState<Item[]>(initialItems);
 const [loggedIn,setLoggedIn]=useState(false);const [loading,setLoading]=useState(api.cloud&&loggedIn);
 const [error,setError]=useState('');const [toast,setToast]=useState('');const [editor,setEditor]=useState<Item|null>(null);
 const [settings,setSettings]=useState(false);const [person,setPerson]=useState('Hepsi');const [pending,setPending]=useState(false);
 const [week,setWeek]=useState(weekStart(today()));const itemsRef=useRef(items);itemsRef.current=items;
 const go=(p:Page)=>{location.hash=p;setPage(p);window.scrollTo({top:0,behavior:'smooth'})};
 const notify=useCallback((s:string)=>setToast(s),[]);
 useEffect(()=>{const fn=()=>setPage(currentPage());window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),4500);return()=>clearTimeout(t)},[toast]);
 const refresh=useCallback(async()=>{if(!api.cloud||!api.currentSession())return;try{const data=await api.loadItems();setItems(data);setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[]);
 useEffect(()=>{if(!api.cloud||!loggedIn)return;void refresh();const focus=()=>{if(document.visibilityState==='visible')void refresh()};window.addEventListener('focus',focus);document.addEventListener('visibilitychange',focus);const t=setInterval(focus,45000);return()=>{window.removeEventListener('focus',focus);document.removeEventListener('visibilitychange',focus);clearInterval(t)}},[loggedIn,refresh]);
 const persist=(next:Item[])=>{if(!api.cloud){try{localStorage.setItem(STORAGE,JSON.stringify(next))}catch{throw new Error('Tarayıcı kaydı yapılamadı. Depolama alanını kontrol et.')}}itemsRef.current=next;setItems(next)};
 const save=async(item:Item)=>{setPending(true);try{const clean=validateItem(item);const result=api.cloud?await api.saveItem(clean):clean;const current=itemsRef.current;persist(current.some(x=>x.id===item.id)?current.map(x=>x.id===item.id?result:x):[result,...current]);setEditor(null);notify('Kaydedildi. Arya haberdar.')}catch(e){notify((e as Error).message);throw e}finally{setPending(false)}};
 const toggle=async(item:Item)=>{if(pending)return;setPending(true);try{const changed={...item,done:!item.done};const result=api.cloud?await api.saveItem(changed):changed;persist(itemsRef.current.map(x=>x.id===result.id?result:x));notify(result.done?'Bir iş daha tamam. Pati onayı!':'Yeniden listeye alındı.')}catch(e){notify((e as Error).message)}finally{setPending(false)}};
 const remove=async(item:Item)=>{setPending(true);try{if(api.cloud)await api.deleteItem(item);persist(itemsRef.current.filter(x=>x.id!==item.id));setEditor(null);notify('Kayıt silindi.')}catch(e){notify((e as Error).message)}finally{setPending(false)}};
 const add=(kind:Kind='task',date='')=>setEditor(newItem(kind,date));
 const taskRows=items.filter(x=>x.kind==='task'&&x.date===today()).sort((a,b)=>Number(a.done)-Number(b.done));
 const needs=items.filter(x=>x.kind==='need'&&!x.done);const notes=items.filter(x=>x.kind==='note').sort((a,b)=>Number(b.pinned)-Number(a.pinned));
 const signout=async()=>{await api.logout();setLoggedIn(false);setItems([]);go('today')};
 if(api.configIncomplete)return <main className="fatal"><img src="./arya-logo.svg" alt="Arya" width="72"/><h1>Bağlantı tamamlanmalı.</h1><p>Ortak veri bağlantısının iki ayarından biri eksik. Bu durumda deneme alanı açılmaz.</p></main>;


 return <div className="site-shell">
  <header className="header"><a className="brand" href="#today" aria-label="Aryaland ana sayfa"><img src="./arya-logo.svg" alt=""/><span>aryaland</span></a><nav aria-label="Ana menü">{nav.map(n=><button key={n.id} className={cx('nav-item',page===n.id&&'active')} disabled={n.id==='budget'} title={n.id==='budget'?'Bütçe şimdilik pasif':undefined} onClick={()=>go(n.id)} aria-current={page===n.id?'page':undefined}><n.icon size={19}/><span>{n.label}</span></button>)}</nav><div className="header-right"><div className="avatars"><button aria-label="Serkan'ın işlerini göster" onClick={()=>{setPerson('Serkan');go('tasks')}}><PersonBadge person="Serkan"/></button><button aria-label="Rabia'nın işlerini göster" onClick={()=>{setPerson('Rabia');go('tasks')}}><PersonBadge person="Rabia"/></button></div><IconButton label="Ev ayarları" onClick={()=>setSettings(true)}><Settings2 size={19}/></IconButton></div></header>
  <main>
   <div className="status-line"><span><Leaf size={13}/> {api.cloud?'Birlikte, aynı evde.':'Deneme alanı · Örnek kayıtlar bu tarayıcıda'}</span>{api.cloud?<button onClick={()=>void refresh()} className="text-button"><RefreshCw size={13}/>Yenile</button>:<button className="text-button" onClick={()=>setSettings(true)}>Nasıl çalışır?</button>}</div>
   {error&&<div className="error-banner" role="alert">{error}<button className="text-button" onClick={()=>void refresh()}>Tekrar dene</button><button className="text-button" onClick={()=>void signout()}>Yeniden giriş</button></div>}
   {loading?<div className="loading"><LoaderCircle className="spin"/>Evimiz hazırlanıyor…</div>:<>
   {page==='today'&&<>
    <section className="hero"><img className="hero-art" src="./art/hero.webp" alt="Arya, beyaz patisini sarkıtarak güneşli pencerenin önünde uzanıyor." fetchPriority="high"/><div className="hero-copy"><div className="eyebrow">{new Intl.DateTimeFormat('tr-TR',{weekday:'long',day:'numeric',month:'long',timeZone:'Europe/Istanbul'}).format(new Date())} <span>·</span> İyi ki evdeyiz.</div><h1>Evimizin küçük<br/>dünyası.</h1><p>Birlikte planla, paylaş, rahatla.</p><button className="button" onClick={()=>add('task',today())}><Plus size={21}/>Yeni ekle</button><span className="hero-heart" aria-hidden="true">♡</span></div></section>
    <section className="dashboard-grid" aria-label="Evimizin özeti">
     <article className="card daily-card"><div className="card-heading"><h2>Bugünün işleri</h2><IconButton label="Tüm ev işlerini aç" onClick={()=>{setPerson('Hepsi');go('tasks')}}><ArrowUpRight size={19}/></IconButton></div><div className="daily-items">{taskRows.length?taskRows.slice(0,4).map(item=><ItemRow key={item.id} item={item} onToggle={toggle} onEdit={setEditor} disabled={pending}/>):<Empty title="Bugün biraz rahatız." text="İstersen yeni bir iş ekleyebilirsin." onAdd={()=>add('task',today())}/>}</div><div className="card-bottom"><span>{taskRows.filter(x=>x.done).length} / {taskRows.length} tamamlandı</span><button className="text-button" onClick={()=>add('task',today())}><Plus size={15}/>İş ekle</button></div><div className="little-line" aria-hidden="true"><span>♡</span></div></article>
     <article className="card week-card"><div className="card-heading"><div><h2>Bu hafta</h2><p className="card-sub">{friendlyDate(week,true)} – {friendlyDate(addDays(week,6),true)}</p></div><div className="button-pair"><IconButton label="Önceki hafta" onClick={()=>setWeek(addDays(week,-7))}><ChevronLeft size={19}/></IconButton><IconButton label="Sonraki hafta" onClick={()=>setWeek(addDays(week,7))}><ChevronRight size={19}/></IconButton></div></div><div className="mini-week">{DAYS.map((day,i)=>{const date=addDays(week,i);const events=items.filter(x=>!x.done&&x.kind!=='note'&&x.kind!=='need'&&isOnDay(x,date));return <div className={cx('mini-day',date===today()&&'current')} key={day}><button className="mini-day-head" onClick={()=>add('event',date)} aria-label={friendlyDate(date)+' etkinlik ekle'}>{day}<span>{fromDay(date).getUTCDate()}</span></button>{events.slice(0,2).map(x=><button key={x.id} className={'event-chip '+x.kind} onClick={()=>setEditor(x)} title={x.title}>{x.kind==='trip'?<Compass size={15}/>:x.category==='Market'?<ShoppingBasket size={15}/>:<House size={15}/>}<span>{x.title}</span></button>)}{events.length>2&&<button className="more-chip" onClick={()=>go('calendar')}>+{events.length-2}</button>}</div>})}</div><img className="week-art" src="./art/window.webp" alt=""/><button className="calendar-link" onClick={()=>go('calendar')}>Takvime git <ArrowUpRight size={14}/></button></article>
     <div className="side-stack"><article className="card budget-card"><div className="card-heading"><h2>Ev bütçesi</h2><LockKeyhole size={17}/></div><div className="budget-cover"><div><span className="locked-label"><LockKeyhole size={22}/>Şimdilik pasif</span><span className="card-sub">Arya defteri dinlendiriyor.</span></div><img src="./art/sleep.webp" alt="Arya bütçe defterinin yanında uyuyor."/></div></article><article className="card mind-card"><div className="card-heading"><h2>Aklımızda</h2><IconButton label="Yeni not ekle" onClick={()=>add('note')}><Plus size={18}/></IconButton></div>{needs.slice(0,1).map(x=><ItemRow key={x.id} item={x} onToggle={toggle} onEdit={setEditor} disabled={pending} compact/>)}{notes.slice(0,1).map(x=><button key={x.id} className="note-preview" onClick={()=>setEditor(x)}><NotebookPen size={18}/><span>{x.title}</span>{x.pinned&&<Pin size={12}/>}</button>)}{needs.length+notes.length===0&&<p className="muted">Aklımıza gelenler burada biriksin.</p>}<button className="text-button view-all" onClick={()=>go('needs')}>Hepsine bak <ArrowUpRight size={14}/></button></article></div>
    </section>
    <section className="home-foot"><div><span className="small-cat">✦</span><span>Birlikte yapılan küçük şeyler, güzel bir ev eder.</span></div><button className="text-button" onClick={()=>go('trips')}><Compass size={17}/>Sıradaki maceramız</button></section>
   </>}
   {page==='tasks'&&<TaskPage items={items} person={person} setPerson={setPerson} add={add} edit={setEditor} toggle={toggle} pending={pending}/>}
   {page==='needs'&&<NeedsPage items={items} add={add} edit={setEditor} toggle={toggle} pending={pending}/>}
   {page==='calendar'&&<CalendarPage items={items} add={add} edit={setEditor}/>}
   {page==='trips'&&<TripsPage items={items} add={add} edit={setEditor}/>}
   {page==='budget'&&<Budget/>}
   </>}
  </main>
  <footer><img src="./arya-logo.svg" alt=""/><span>Arya gözetiminde, sevgiyle.</span><span className="footer-mode">{api.cloud?'Ortak evimiz':'İlk deneme sürümü'}</span></footer>
  {editor&&<Editor item={editor} existing={items.some(x=>x.id===editor.id)} pending={pending} onSave={save} onDelete={remove} onClose={()=>{if(!pending)setEditor(null)}}/>}
  {settings&&<Modal title="Evimizin ayarları" onClose={()=>setSettings(false)}><div className="settings-intro"><img src="./arya-logo.svg" alt="Arya"/><div><h3>Aryaland</h3><p>Serkan, Rabia ve evin asıl sahibi Arya.</p></div></div><section className="settings-section"><h3>{api.cloud?'Ortak ev bağlantısı':'Burası deneme alanımız'}</h3><p>{api.cloud?'Kayıtlar ev üyeleri arasında paylaşılır. Açık ekrandaki listeler düzenli olarak ve pencereye döndüğünde yenilenir.':'İşleri, takvimi, ihtiyaçları ve gezileri deneyebilirsin. Buradaki kayıtlar yalnızca bu tarayıcıda saklanır; diğer cihazlarla paylaşılmaz. Gerçek muhasebe bilgilerini deneme alanına girme.'}</p>{!api.cloud&&<p>Bütçe şimdilik pasif. Bu sürümde giriş ve şifre yönetimi yok.</p>}</section><section className="settings-section"><h3>Listelerimiz</h3><p>Bu dosya işleri, ihtiyaçları, notları ve planları içerir. Muhasebe kayıtları dahil değildir.</p><div className="action-wrap"><button className="button secondary" onClick={()=>downloadJSON(items)}><Download size={17}/>Listeleri dışa aktar</button>{!api.cloud&&<label className="button secondary file-label"><Upload size={17}/>Listeleri içe aktar<input type="file" accept="application/json,.json" onChange={async e=>{const file=e.target.files?.[0];e.target.value='';if(!file)return;try{if(file.size>2e6)throw new Error('Dosya 2 MB sınırını aşıyor.');const data=JSON.parse(await file.text());if(data.format!=='aryaland-lists-v1'||!Array.isArray(data.items)||data.items.length>2000)throw new Error('Aryaland liste dosyası seç.');const incoming=data.items.map(validateItem);if(new Set(incoming.map((x:Item)=>x.id)).size!==incoming.length)throw new Error('Dosyada tekrarlanan kayıt kimlikleri var.');if(!window.confirm('Bu tarayıcıdaki '+items.length+' kayıt, dosyadaki '+incoming.length+' kayıtla değiştirilecek. Devam edilsin mi?'))return;persist(incoming);notify('Listeler içe aktarıldı.')}catch(err){notify((err as Error).message)}}}/></label>}</div></section>{api.cloud?<button className="button secondary" onClick={()=>{setSettings(false);void signout()}}><LogOut size={17}/>Çıkış yap</button>:<button className="text-button danger-text" onClick={()=>{if(window.confirm('Bu tarayıcıdaki deneme kayıtları silinip başlangıç örnekleri yüklenecek. Devam edilsin mi?')){try{persist(seedItems());notify('Deneme alanı yenilendi.')}catch(e){notify((e as Error).message)}}}}><RefreshCw size={14}/>Örnekleri baştan yükle</button>}</Modal>}
  {toast&&<div className="toast" role="status"><span>{toast}</span><button onClick={()=>setToast('')} aria-label="Bildirimi kapat"><X size={16}/></button></div>}
 </div>
}

function ItemRow({item,onToggle,onEdit,disabled=false,compact=false}:{item:Item;onToggle:(i:Item)=>void;onEdit:(i:Item)=>void;disabled?:boolean;compact?:boolean}){return <div className={cx('item-row',item.done&&'done',compact&&'compact')}><button className={cx('checkbox',item.done&&'checked')} aria-label={item.title+(item.done?' yeniden aç':' tamamla')} aria-pressed={item.done} disabled={disabled} onClick={()=>onToggle(item)}>{item.done&&<Check size={18}/>}</button><button className="item-title" onClick={()=>onEdit(item)}><span>{item.title}</span>{!compact&&item.date&&<small className={cx(!item.done&&item.date<today()&&'overdue')}>{item.date<today()&&!item.done?'Gecikti · ':''}{friendlyDate(item.date,true)}</small>}</button>{!compact&&<PersonBadge person={item.assignee}/>}</div>}
function PageHead({eyebrow,title,description,onAdd,label='Yeni ekle'}:{eyebrow:string;title:string;description:string;onAdd?:()=>void;label?:string}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{description}</p></div>{onAdd&&<button className="button" onClick={onAdd}><Plus size={19}/>{label}</button>}</div>}
type CommonProps={items:Item[];add:(k:Kind,date?:string)=>void;edit:(i:Item)=>void};
function TaskPage({items,person,setPerson,add,edit,toggle,pending}:CommonProps&{person:string;setPerson:(p:string)=>void;toggle:(i:Item)=>void;pending:boolean}){
 const [status,setStatus]=useState('Bekleyen');const [q,setQ]=useState('');
 const tasks=items.filter(x=>x.kind==='task');const filtered=tasks.filter(x=>(person==='Hepsi'||x.assignee===person)&&(status==='Hepsi'||x.done===(status==='Tamamlanan'))&&x.title.toLocaleLowerCase('tr').includes(q.toLocaleLowerCase('tr'))).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));
 return <><PageHead eyebrow="PAYLAŞINCA HAFİFLER" title="Ev işleri & ricalar" description="Kim neyi üstlensin? Küçük işler, ortak bir düzen." onAdd={()=>add('task',today())} label="İş ekle"/><div className="toolbar"><div className="segmented">{['Bekleyen','Tamamlanan','Hepsi'].map(s=><button className={status===s?'selected':''} key={s} onClick={()=>setStatus(s)}>{s}</button>)}</div><div className="filters"><label className="search"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="İşlerde ara" aria-label="İşlerde ara"/></label><select value={person} onChange={e=>setPerson(e.target.value)} aria-label="Sorumlu kişi"><option>Hepsi</option><option>Serkan</option><option>Rabia</option><option>Birlikte</option></select></div></div><div className="two-column"><section className="card list-card"><div className="card-heading"><h2>{status==='Tamamlanan'?'Ellerimize sağlık':status==='Hepsi'?'Bütün işlerimiz':'Sıradaki işler'}</h2><span className="count">{filtered.length}</span></div>{filtered.length?filtered.map(x=><ItemRow key={x.id} item={x} onToggle={toggle} onEdit={edit} disabled={pending}/>):<Empty title="Liste tertemiz." text="Bu filtrede gösterilecek iş yok." onAdd={()=>add('task',today())}/>}</section><aside className="card cozy-aside"><img src="./art/sleep.webp" alt="Uyuyan Arya"/><h2>Birlikte daha kolay.</h2><p>İşleri paylaşalım, dinlenmeye de yer kalsın.</p><div className="progress-caption"><span>Tamamlanan işler</span><strong>{tasks.filter(x=>x.done).length}/{tasks.length}</strong></div><progress value={tasks.filter(x=>x.done).length} max={tasks.length||1}/></aside></div></>
}
function NeedsPage({items,add,edit,toggle,pending}:CommonProps&{toggle:(i:Item)=>void;pending:boolean}){
 const [tab,setTab]=useState('İhtiyaçlar');const [showDone,setShowDone]=useState(false);const needs=items.filter(x=>x.kind==='need'&&(showDone||!x.done));const notes=items.filter(x=>x.kind==='note').sort((a,b)=>Number(b.pinned)-Number(a.pinned));
 return <><PageHead eyebrow="AKLIMIZDA KALMASIN" title="İhtiyaçlar & notlar" description="Eksilenler, alınacaklar ve unutmamamız gereken küçük şeyler." onAdd={()=>add(tab==='Notlar'?'note':'need')} label={tab==='Notlar'?'Not ekle':'İhtiyaç ekle'}/><div className="toolbar"><div className="segmented">{['İhtiyaçlar','Notlar'].map(s=><button key={s} className={tab===s?'selected':''} onClick={()=>setTab(s)}>{s}</button>)}</div>{tab==='İhtiyaçlar'&&<label className="check-label"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>Alınanları da göster</label>}</div>{tab==='İhtiyaçlar'?<div className="needs-grid">{needs.length?Array.from(new Set(needs.map(x=>x.category))).map(c=><article className="card list-card" key={c}><div className="card-heading"><h2>{c}</h2><ShoppingBasket size={20}/></div>{needs.filter(x=>x.category===c).map(x=><ItemRow item={x} key={x.id} onToggle={toggle} onEdit={edit} disabled={pending}/>)}</article>):<section className="card full"><Empty title="Evde her şey tamam." text="Eksilen bir şey olursa burada buluşalım." onAdd={()=>add('need')}/></section>}</div>:<div className="notes-grid">{notes.length?notes.map(x=><button className={cx('card note-card',x.pinned&&'pinned')} key={x.id} onClick={()=>edit(x)}><div className="note-top"><span>{x.category}</span>{x.pinned?<Pin size={18}/>:<NotebookPen size={18}/>}</div><h2>{x.title}</h2><p>{x.details||'Detay eklemek için aç.'}</p><div className="note-bottom"><PersonBadge person={x.assignee}/><span>{x.date?friendlyDate(x.date):'Evimize bir not'}</span><ArrowUpRight size={17}/></div></button>):<section className="card full"><Empty title="İlk not bizden olsun." text="Bir fikir, bir hatırlatma, küçük bir rica…" onAdd={()=>add('note')}/></section>}</div>}</>
}
function CalendarPage({items,add,edit}:CommonProps){
 const [anchor,setAnchor]=useState(today());const [mode,setMode]=useState('Ay');const [filter,setFilter]=useState('Hepsi');
 const d=fromDay(anchor);const first=dayKey(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),1,12)));const start=mode==='Hafta'?weekStart(anchor):weekStart(first);
 const dates=Array.from({length:mode==='Hafta'?7:42},(_,i)=>addDays(start,i));
 const title=mode==='Ay'?new Intl.DateTimeFormat('tr-TR',{month:'long',year:'numeric',timeZone:'UTC'}).format(d):friendlyDate(start)+' – '+friendlyDate(addDays(start,6));
 const move=(dir:number)=>setAnchor(mode==='Hafta'?addDays(anchor,7*dir):dayKey(new Date(Date.UTC(d.getUTCFullYear(),d.getUTCMonth()+dir,1,12))));
 return <><PageHead eyebrow="GÜZEL GÜNLERE YER AÇALIM" title="Ortak takvimimiz" description="Ev işleri, buluşmalar ve küçük kaçamaklar bir arada." onAdd={()=>add('event',today())} label="Plan ekle"/><div className="toolbar calendar-toolbar"><div className="month-nav"><IconButton label="Önceki dönem" onClick={()=>move(-1)}><ChevronLeft/></IconButton><h2>{title}</h2><IconButton label="Sonraki dönem" onClick={()=>move(1)}><ChevronRight/></IconButton><button className="text-button" onClick={()=>setAnchor(today())}>Bugün</button></div><div className="filters"><select value={filter} onChange={e=>setFilter(e.target.value)} aria-label="Takvim türü"><option>Hepsi</option><option value="task">Ev işleri</option><option value="event">Etkinlikler</option><option value="trip">Geziler</option></select><div className="segmented">{['Ay','Hafta'].map(m=><button key={m} className={mode===m?'selected':''} onClick={()=>setMode(m)}>{m}</button>)}</div></div></div><section className="card calendar-container"><div className={cx('calendar',mode==='Hafta'&&'week-mode')}><div className="calendar-labels">{DAYS.map(x=><div key={x}>{x}</div>)}</div><div className="calendar-grid">{dates.map(date=>{const events=items.filter(x=>['task','event','trip'].includes(x.kind)&&(filter==='Hepsi'||x.kind===filter)&&isOnDay(x,date));return <div key={date} className={cx('calendar-day',date.slice(0,7)!==anchor.slice(0,7)&&mode==='Ay'&&'other-month',date===today()&&'current')}><button className="day-number" onClick={()=>add('event',date)} aria-label={friendlyDate(date)+' yeni plan'}>{fromDay(date).getUTCDate()}<Plus size={12}/></button><div className="day-events">{events.map(x=><button className={cx('calendar-event',x.kind,x.done&&'done')} key={x.id} onClick={()=>edit(x)} title={x.title}><span className="event-dot"/>{x.title}</button>)}</div></div>})}</div></div><div className="calendar-legend"><span><i className="task"/>Ev işleri</span><span><i className="event"/>Etkinlikler</span><span><i className="trip"/>Geziler</span><span className="muted">Bir güne dokun, plan ekle.</span></div></section></>
}
function TripsPage({items,add,edit}:CommonProps){
 const [past,setPast]=useState(false);const trips=items.filter(x=>x.kind==='trip'&&(past||!x.date||(x.endDate||x.date)>=today())).sort((a,b)=>(a.date||'9999').localeCompare(b.date||'9999'));
 return <><PageHead eyebrow="BİRAZ DA DIŞARI ÇIKALIM" title="Sıradaki maceramız" description="Bir yürüyüş, yeni bir şehir, birlikte biriktireceğimiz anılar." onAdd={()=>add('trip',today())} label="Gezi planla"/><div className="toolbar"><span className="muted">{trips.length} gezi planı</span><label className="check-label"><input type="checkbox" checked={past} onChange={e=>setPast(e.target.checked)}/>Geçmiş gezileri göster</label></div><div className="trips-grid">{trips.length?trips.map((x,i)=><article className="card trip-card" key={x.id}><div className={'trip-scene scene-'+i%3}><Compass size={66} strokeWidth={.85}/><span className="trip-date"><CalendarDays size={14}/>{x.date?friendlyDate(x.date)+(x.endDate&&x.endDate!==x.date?' – '+friendlyDate(x.endDate):''):'Tarihi birlikte seçelim'}</span><span className="trip-scene-lines" aria-hidden="true"/></div><div className="trip-body"><div className="eyebrow"><MapPin size={13}/>{x.place||'Rotamız henüz açık'}</div><h2>{x.title}</h2><p>{x.details||'Rotayı, hazırlıkları ve fikirleri bu plana ekleyelim.'}</p><div className="trip-bottom"><PersonBadge person={x.assignee}/><button className="text-button" onClick={()=>edit(x)}>Planı aç <ArrowUpRight size={16}/></button></div></div></article>):<section className="card full"><Empty title="Yeni bir rota çizelim." text="Küçük bir gezi bile güzel bir başlangıç." onAdd={()=>add('trip',today())} label="Gezi planla"/></section>}</div></>
}

function Editor({item,existing,pending,onSave,onDelete,onClose}:{item:Item;existing:boolean;pending:boolean;onSave:(x:Item)=>Promise<void>;onDelete:(x:Item)=>void;onClose:()=>void}){
 const [draft,setDraft]=useState({...item});const [confirm,setConfirm]=useState(false);const [error,setError]=useState('');
 const change=<K extends keyof Item>(k:K,v:Item[K])=>setDraft(p=>({...p,[k]:v}));
 return <Modal title={existing?'Birlikte düzenleyelim':'Yeni bir şey ekleyelim'} onClose={onClose}><form onSubmit={async e=>{e.preventDefault();try{setError('');await onSave(draft)}catch(err){setError((err as Error).message)}}}><div className="form-grid"><label className="field">Ne ekliyoruz?<select value={draft.kind} disabled={existing} onChange={e=>change('kind',e.target.value as Kind)}>{Object.entries(kinds).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></label><label className="field">Kim ilgilensin?<select value={draft.assignee} onChange={e=>change('assignee',e.target.value as Person)}><option>Birlikte</option><option>Serkan</option><option>Rabia</option></select></label><label className="field full">Başlık<input autoFocus required maxLength={120} value={draft.title} onChange={e=>change('title',e.target.value)} placeholder={draft.kind==='trip'?'Nereye kaçıyoruz?':'Aklımızdaki şey…'}/></label><label className="field">{draft.kind==='trip'?'Başlangıç':'Tarih'}<input type="date" value={draft.date} required={['event','trip'].includes(draft.kind)} onChange={e=>change('date',e.target.value)}/></label>{draft.kind==='trip'?<label className="field">Bitiş<input type="date" value={draft.endDate} min={draft.date||undefined} onChange={e=>change('endDate',e.target.value)}/></label>:<label className="field">Kategori<select value={draft.category} onChange={e=>change('category',e.target.value)}>{categories.map(c=><option key={c}>{c}</option>)}</select></label>}{draft.kind==='trip'&&<label className="field full">Nerede?<input value={draft.place} onChange={e=>change('place',e.target.value)} placeholder="Şehir, rota veya buluşma yeri" maxLength={250}/></label>}<label className="field full">{draft.kind==='trip'?'Rota, hazırlıklar ve notlar':'Biraz daha detay'}<textarea rows={4} value={draft.details} onChange={e=>change('details',e.target.value)} placeholder="İstersen birkaç not bırak…" maxLength={3000}/></label>{draft.kind==='note'&&<label className="check-label full"><input type="checkbox" checked={draft.pinned} onChange={e=>change('pinned',e.target.checked)}/>Bu notu üste sabitle</label>}</div>{error&&<p className="form-error" role="alert">{error}</p>}<div className="modal-actions">{existing&&<button type="button" className="text-button danger-text" onClick={()=>setConfirm(true)} disabled={pending}><Trash2 size={16}/>Sil</button>}<div className="spacer"/><button className="button secondary" type="button" onClick={onClose} disabled={pending}>Vazgeç</button><button className="button" disabled={pending}>{pending?<LoaderCircle className="spin" size={17}/>:<Check size={17}/>}Kaydet</button></div>{confirm&&<div className="delete-confirm"><p>“{draft.title}” kalıcı olarak silinsin mi?</p><button type="button" className="text-button" onClick={()=>setConfirm(false)}>Vazgeç</button><button type="button" className="button danger small" onClick={()=>onDelete(item)} disabled={pending}>Evet, sil</button></div>}</form></Modal>
}

function Budget(){return <><PageHead eyebrow="ŞİMDİLİK MOLA" title="Ev bütçesi" description="Bu bölüm şimdilik pasif."/><section className="card vault"><img src="./art/sleep.webp" alt="Arya bütçe defterinin üzerinde uyuyor."/><div><h2>Arya defteri dinlendiriyor.</h2><p>Gelir-gider kaydı, giriş ve şifre yönetimini daha sonra ele alacağız.</p></div></section></>}
function downloadJSON(items:Item[]){const blob=new Blob([JSON.stringify({format:'aryaland-lists-v1',exportedAt:new Date().toISOString(),items:items.map(({updatedAt,...x})=>x)},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aryaland-listeler-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
